import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (path) => fs.readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8');
const authority = read('src/features/delegations/effectiveAuthority.ts');
const filters = read('src/features/delegations/operationalWorkspaceFilters.ts');
const context = read('src/context/AppContext.tsx');
const app = read('src/App.tsx');
const dashboard = read('src/pages/DashboardPage.tsx');
const quickActionModel = read('src/components/dashboard/quickActionModel.ts');
const reports = read('src/pages/ReportsPage.tsx');
const templates = read('src/pages/TemplatesPage.tsx');
const requests = read('src/pages/MyRequestsPage.tsx');
const reportRepo = read('src/features/reports/reportRepository.ts');
const reportService = read('src/features/reports/reportService.ts');
const templateMapper = read('src/features/templates/mappers/templateSerializer.ts');
const navbar = read('src/components/layout/Navbar.tsx');
const signatureModal = read('src/components/report/ReportSignatureModal.tsx');
const uploadedReport = read('src/components/reports/UploadedReportModal.tsx');
const templateBuilder = read('src/components/template-builder/TemplateBuilder.tsx');
const templateCard = read('src/components/templates/TemplateCard.tsx');
const templateSelection = read('src/features/templates/templateSelection.ts');
const templateCardContent = templateCard.slice(templateCard.indexOf('return ('), templateCard.indexOf('{/* Tag chips'));
const templateDetail = read('src/components/templates/TemplateDetailModal.tsx');
const sidebar = read('src/components/layout/Sidebar.tsx');
const requestDrawer = read('src/components/requests/RequestDetailDrawer.tsx');
const recipientDirectory = read('src/features/reports/reportRepository.ts');
const insightsRevision = read('src/components/insights/TemplateUsageActions.tsx');

assert.match(authority, /context\.mode === 'delegated'[\s\S]*context\.effectivePermissions/);
assert.match(authority, /context\.mode === 'delegated'[\s\S]*\? context\.effectivePermissions[\s\S]*: context\.actorPermissions/);
assert.match(filters, /operationalSubjectUserId === undefined[\s\S]*row\.createdById/);
assert.match(filters, /row\.operationalSubjectUserId/);

assert.match(reportRepo, /'operational_subject_user_id'/);
assert.match(recipientDirectory, /rpc\('list_report_recipient_directory'\)/, 'recipient selection uses the canonical backend directory');
assert.match(reportService, /operationalSubjectUserId: row\.operational_subject_user_id/);
assert.match(templateMapper, /operationalSubjectUserId: row\.operational_subject_user_id/);
assert.match(context, /const currentUser = authenticatedPrincipal/);
assert.match(context, /createdById: currentUser\.id/);
assert.match(context, /reportPersistenceRef\.current\.ensure\(payload\)/);
assert.match(context, /reportService\.create\(tplId, initialData, initialTitle\)/);
assert.doesNotMatch(context, /p_operational_subject_user_id|operational_subject_user_id\s*:/, 'client does not supply the operational subject to authoring RPCs');

assert.match(context, /canSaveTemplateDraft = \(existingId\?: string\) => canAuthorTemplate\(hasOperationalPermission, existingId\)/);
assert.match(context, /hasOperationalPermission\('templates\.submit'\)/);
assert.match(context, /operationalActionBlocked\('reports\.create'\)/);
assert.match(context, /const requiredPermission = markAsCompleted \? 'reports\.complete' : 'reports\.edit_draft'/);
assert.match(context, /operationalActionBlocked\(requiredPermission\)/);
assert.match(context, /operationalActionBlocked\('reports\.send'\)/);
assert.match(context, /Report comments are not part of the delegated authoring contract/);
assert.match(context, /const addReportComment = async[\s\S]*if \(isDelegatedMode \|\| workspaceLoadingRef\.current/);

assert.match(reports, /hasOperationalPermission\('reports\.create'\)/);
assert.match(reports, /rep\.sourceType === 'template'.*hasOperationalPermission\('reports\.edit_draft'\)/);
assert.match(reports, /hasOperationalPermission\('reports\.complete'\)/);
assert.match(reports, /hasOperationalPermission\('reports\.send'\)/);
assert.match(reports, /!isDelegatedMode && rep\.sourceType === 'uploaded'/, 'uploaded Report authoring remains actor-only');
assert.match(templates, /canAuthorTemplate\(hasOperationalPermission\)/, 'template creation entry uses operational templates.create only');
assert.match(app, /canAuthorTemplates = canAuthorTemplate\(hasOperationalPermission, draftToEdit\?\.id\)/);
assert.match(templateBuilder, /onCreateVersion=\{hasOperationalPermission\('templates\.create'\)/);
assert.match(requests, /canOpenTemplateStudio = canEditTemplateDraft\(hasOperationalPermission\)/);
assert.match(requests, /canAuthorTemplate\(hasOperationalPermission\)/);
assert.match(requestDrawer, /canEditTemplateDraft\(hasOperationalPermission\)/);
assert.match(sidebar, /canAuthorTemplate\(hasOperationalPermission\)/);
assert.doesNotMatch(context, /canSaveTemplateDraft[\s\S]{0,120}studio\.access/);
assert.match(templateBuilder, /templateService\.createRevision\(templateState\.id\)/);
assert.match(templateBuilder, /governanceLevel=\{\(isDelegatedMode \? authorityContext\?\.authority\.governanceLevel/);
assert.match(templateBuilder, /const effectiveAuthorRoleKey = isDelegatedMode[\s\S]*authorityContext\?\.authority\.roleKey[\s\S]*currentUser\.roleKey \|\| currentUser\.role[\s\S]*activeRoleKeys: effectiveAuthorRoleKey \? \[effectiveAuthorRoleKey\] : \[\]/, 'signature readiness follows effective authority while retaining actor role metadata');
assert.match(templateBuilder, /createdByRole: currentUser\.role/, 'template creator provenance remains the authenticated actor');
assert.doesNotMatch(templateBuilder, /roleName\s*===\s*['"]Director['"]|governanceLevel\s*===\s*['"]Director['"]/i, 'submission is not hard-coded to Director');
assert.match(context, /result as any\)\.status === 'approved'[\s\S]*status === 'Approved'/, 'submit UX recognizes direct publish results from backend governance');
assert.match(insightsRevision, /templateInsightsService\.createTemplateRevision\(template\.templateId\)/, 'the Insights-owned revision flow remains distinct and actor-governed');
assert.match(app, /selectedTemplateForFill && canCreateTemplateBackedReport\(hasOperationalPermission\)/);
assert.match(authority, /hasPermission\('reports\.create'\)[\s\S]*hasPermission\('reports\.view_own'\)[\s\S]*hasPermission\('templates\.view_approved'\)[\s\S]*hasPermission\('templates\.use'\)/, 'Use Template matches the complete backend create-report permission contract');
assert.match(context, /canCreateTemplateBackedReport\(hasOperationalPermission\)/, 'context blocks direct create-modal and mutation calls without the canonical permission set');
assert.match(quickActionModel, /title: 'Create Report',[\s\S]*visible: input\.hasOperationalPermission\('reports\.create'\)/, 'Dashboard Create Report entry follows effective reports.create');
assert.match(reports, /const canStartReportCreation = hasOperationalPermission\('reports\.create'\)/, 'Reports Create Report entry follows effective reports.create');
assert.match(context, /if \(view === 'reports'\) return hasOperationalPermission\('reports\.create'\)/, 'report creation permission can open the existing Reports action surface');
assert.match(reports, /Approved-template access is required to start a report from a template/);
assert.match(templateCard, /selectTemplateFromLibrary\([\s\S]*canUseTemplate[\s\S]*openFillReportModal[\s\S]*openTemplateDetail/, 'TemplateCard reuses the shared existing Use/Preview selection behavior');
assert.match(templateSelection, /if \(canUseTemplate && !template\.isPaused\)[\s\S]*onUse\(template\)[\s\S]*onPreview\(template\)/, 'template selection uses the existing Fill Report path or preview, and blocks paused Use');
assert.match(templateCardContent, /<button[\s\S]*onClick=\{handleTemplateSelect\}[\s\S]*aria-label=\{canUseTemplate/ , 'template card content is keyboard-operable and selects the existing authorized flow');
assert.match(templateCard, /canCreateTemplateBackedReport\(hasOperationalPermission\)[\s\S]*onClick=\{\(\) => openFillReportModal\(template\)\}[\s\S]*disabled=\{template\.isPaused\}/, 'Template Use continues through the existing fill handler and is disabled only when paused');
assert.match(templateCard, /onClick=\{\(\) => openTemplateDetail\(template\)\}/, 'Template preview continues through the existing detail modal');
assert.match(templateDetail, /canCreateTemplateBackedReport\(hasOperationalPermission\)[\s\S]*onClick=\{handleUseTemplate\}/);
assert.match(templates, /onClick=\{\(\) => setSelectedCategory\(cat\.id\)\}/, 'category navigation remains the existing interactive filter action');
const dashboardPopularStart = dashboard.indexOf('{/* Popular Report Templates */}');
const dashboardPopularEnd = dashboard.indexOf('<WorkflowMonitor', dashboardPopularStart);
const dashboardPopular = dashboard.slice(dashboardPopularStart, dashboardPopularEnd);
assert.match(dashboardPopular, /<button[\s\S]*onClick=\{\(\) => selectTemplateFromLibrary\([\s\S]*tpl[\s\S]*openFillReportModal[\s\S]*openTemplateDetail[\s\S]*disabled=\{!hasOperationalPermission\('templates\.view_approved'\)\}/, 'the actual Dashboard popular-template row is keyboard interactive and uses canonical handlers');
assert.doesNotMatch(templateCard, /disabled=\{isDelegatedMode\}|isDelegatedMode\s*\?\s*false/);
assert.match(app, /selectedReportForSend && hasOperationalPermission\('reports\.send'\) && \(!isDelegatedMode \|\| selectedReportForSend\.sourceType === 'template'\)/);
assert.match(context, /if \(isSupabasePrincipal\(currentUser\)\) return myTemplates/);
assert.match(requests, /belongsToOperationalSubject\(template, operationalSubjectUserId \?\? ''\)/);
assert.match(dashboard, /hasPermission=\{hasOperationalPermission\}/);

assert.match(context, /confirmsDelegatedAuthority\(confirmedContext, delegationId\)/);
assert.match(context, /confirmsOwnAuthority\(confirmedContext\)/);
assert.match(context, /Your authority changed successfully, but some workspace data could not be refreshed\. Please retry\./);
assert.match(context, /requestId === authorityContextRequest\.current && workspaceRequest === workspaceLoadRequest\.current/);
assert.match(context, /workspaceRequest === workspaceLoadRequest\.current/);
assert.match(context, /const operationalActionBlocked = \(permission: PermissionKey\) =>/);
assert.match(context, /const operationalActionBlocked = \(permission: PermissionKey\) =>[\s\S]*authorityContextStatus !== 'ready'[\s\S]*operationalWorkspaceLoading/);
assert.match(navbar, /disabled=\{returningToOwn \|\| operationalWorkspaceLoading \|\| authorityContextStatus !== 'ready'\}/);
const selectStart = context.indexOf('const selectDelegationContext =');
const selectEnd = context.indexOf('const openDelegatedReportNotification', selectStart);
const selectFlow = context.slice(selectStart, selectEnd);
assert.ok(selectFlow.indexOf('confirmsDelegatedAuthority(confirmedContext, delegationId)') < selectFlow.indexOf('loadWorkspaceForContext(confirmedContext'), 'Act As success is based on canonical context before hydration');
assert.ok(selectFlow.indexOf('loadWorkspaceForContext(confirmedContext') < selectFlow.indexOf('return true'), 'secondary workspace hydration cannot turn confirmed Act As into failure');
assert.match(selectFlow, /if \(refreshedContext\?\.mode === 'delegated'\)[\s\S]*This delegated authority is no longer active/);
const clearStart = context.indexOf('const clearDelegationContext =');
const clearEnd = context.indexOf('useEffect(() => {\n    if (authorityContextStatus', clearStart);
const clearFlow = context.slice(clearStart, clearEnd);
assert.ok(clearFlow.indexOf('confirmsOwnAuthority(confirmedContext)') < clearFlow.indexOf('loadWorkspaceForContext(confirmedContext'), 'Return success is based on canonical own context before hydration');
assert.ok(clearFlow.indexOf('loadWorkspaceForContext(confirmedContext') < clearFlow.indexOf('return true'), 'secondary workspace hydration cannot turn confirmed Return into failure');
assert.match(clearFlow, /We could not return to your own authority\. Please try again\./, 'a genuine canonical transition mismatch retains a safe failure');
assert.match(context, /requestId === authorityContextRequest\.current/);
assert.match(context, /expectedWorkspaceRequest === workspaceLoadRequest\.current/);
const workspaceLoaderStart = context.indexOf('const loadWorkspaceForContext = async');
const workspaceLoaderEnd = context.indexOf('const refreshAuthorityContext', workspaceLoaderStart);
const workspaceLoader = context.slice(workspaceLoaderStart, workspaceLoaderEnd);
assert.match(workspaceLoader, /setAuthorityContextStatus\('ready'\)/);
assert.match(workspaceLoader, /catch[\s\S]*Your authority changed successfully, but some workspace data could not be refreshed\. Please retry\./);
assert.match(workspaceLoader, /finally[\s\S]*setOperationalWorkspaceLoading\(false\)/);
assert.doesNotMatch(workspaceLoader, /We could not (?:switch|return) to this delegated authority|We could not return to your own authority/);

assert.match(signatureModal, /signatureService\.getMySignatureProfile\(\)/);
assert.match(signatureModal, /profile\.userId !== currentUser\.id/);
assert.match(context, /listNotifications\(currentUser\.id\)/);
assert.match(uploadedReport, /currentUser\.id|useApp\(\)/);
assert.doesNotMatch(context, /setUserRole|updatePermanentRole|assignUserRole/);

console.log('delegated authoring, operational ownership, personal surfaces, and transition static checks passed');
