import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(path, 'utf8');
const context = read('src/context/AppContext.tsx');
const configRepository = read('src/features/configuration/repositories/configurationRepository.ts');
const configService = read('src/features/configuration/services/configurationService.ts');
const adminRead = read('src/features/admin/repositories/adminReadRepository.ts');
const adminMutation = read('src/features/admin/repositories/adminMutationRepository.ts');
const adminService = read('src/features/admin/services/adminService.ts');
const accessUi = read('src/components/admin/InsightsAccessManagement.tsx');
const accessTypes = read('src/features/insights/featureAccessTypes.ts');
const featureUi = read('src/components/admin/AdminFeatureManagement.tsx');
const adminShell = read('src/components/admin/AdminLayout.tsx');
const adminSidebar = read('src/components/admin/AdminSidebar.tsx');
const app = read('src/App.tsx');
const sidebar = read('src/components/layout/Sidebar.tsx');
const page = read('src/pages/InsightsPage.tsx');
const templateActions = read('src/components/insights/TemplateUsageActions.tsx');
const deleteAction = read('src/components/templates/DeleteTemplateAction.tsx');
const all = [context, configRepository, configService, adminRead, adminMutation, adminService, accessUi, accessTypes, featureUi, adminShell, adminSidebar, app, sidebar, page, templateActions, deleteAction].join('\n');

assert.match(configRepository, /rpc\('current_feature_access', \{ p_feature_key: featureKey \}\)/);
assert.match(context, /currentFeatureAccess\('insights'\)/);
assert.match(context, /status: 'loading', enabled: false, insightsAllowed: false/);
assert.match(context, /window\.addEventListener\('focus'/);
assert.match(context, /TOKEN_REFRESHED/);
assert.match(sidebar, /canAccessInsights\(insightsAccess\)/);
assert.match(app, /case 'insights':[\s\S]*canAccessInsights\(insightsAccess\)/);
assert.match(page, /const allowed = canAccessInsights\(insightsAccess\)/);
assert.match(page, /if \(!allowed\) return;/, 'analytics calls are guarded by effective access');
assert.match(adminRead, /rpc\('admin_list_feature_role_access'[\s\S]*p_feature_key: 'insights'[\s\S]*p_search: search\.trim\(\) \|\| null[\s\S]*p_limit: limit[\s\S]*p_offset: offset/);
assert.match(adminRead, /rpc\('admin_list_feature_user_access'[\s\S]*p_feature_key: 'insights'[\s\S]*p_search: search\.trim\(\) \|\| null[\s\S]*p_limit: limit[\s\S]*p_offset: offset/);
assert.match(adminMutation, /admin_set_feature_role_access'[\s\S]*p_feature_key: 'insights'[\s\S]*p_role_id: roleId[\s\S]*p_allowed: allowed/);
assert.match(adminMutation, /admin_set_feature_user_override'[\s\S]*p_feature_key: 'insights'[\s\S]*p_user_id: userId[\s\S]*p_override: override/);
assert.match(accessUi, /setSearch\(searchInput\.trim\(\)\)[\s\S]*setOffset\(0\)/);
assert.match(accessUi, /PAGE_SIZE = 25/);
assert.match(accessUi, /requestSequence/);
assert.match(accessUi, /role\.roleId/);
assert.match(accessUi, /user\.userId/);
assert.match(accessUi, /!role\.configurable/);
assert.match(accessUi, /user\.protectedAdmin/);
assert.match(accessUi, /override: FeatureUserOverride/);
assert.match(accessTypes, /'inherit' \| 'allow' \| 'deny'/);
assert.doesNotMatch(accessUi, /Director|Manager|Employee|\.from\(['"]profiles['"]\)|\.from\(['"]roles['"]\)/);
assert.match(featureUi, /feat\.feature_key === 'insights'[\s\S]*Manage Access/);
assert.match(featureUi, /handleToggle\(feat\.feature_key, isEnabled\)/, 'global feature toggle remains its existing independent action');
assert.match(adminSidebar, /id: 'insights', label: 'Insights'/);
assert.match(adminShell, /activeTab === 'insights'[\s\S]*<InsightsPage \/>/);
assert.match(adminShell, /tab !== 'insights'[\s\S]*refreshInsightsAccess\(\)/, 'Admin Insights navigation revalidates current canonical access');
assert.doesNotMatch(adminShell, /AdminInsightsPage|AdminAnalyticsClone/);
assert.match(adminShell, /activeTab === 'insights-access'[\s\S]*<InsightsAccessManagement/);
assert.match(deleteAction, /canAccessInsights\(insightsAccess\)/);
assert.match(templateActions, /canAccessInsights\(insightsAccess\)/);
assert.doesNotMatch(all, /canViewTemplateInsights|reports\.view_organization['"]\)\s*&&\s*hasPermission\(['"]templates\.view_approved/);
assert.doesNotMatch(accessUi, /roleName\s*===|roleKey\s*===|role_key\s*===/);
assert.doesNotMatch(accessUi, /fetch.*all.*users|load.*all.*roles/i);

console.log('Phase 099 Insights access static checks passed.');
