import React, { useEffect, useMemo, useState } from 'react';
import { Edit3, Pin, Plus, Search, StickyNote as StickyIcon, Trash2, X } from 'lucide-react';
import { stickyNotesService } from '../features/sticky-notes/stickyNotesService';
import type { StickyNote, StickyNoteColor, StickyNoteInput } from '../features/sticky-notes/stickyNotesTypes';

const colors: StickyNoteColor[] = ['yellow', 'blue', 'green', 'rose', 'purple'];
const colorClass: Record<StickyNoteColor, string> = { yellow: 'bg-amber-50 border-amber-200', blue: 'bg-blue-50 border-blue-200', green: 'bg-emerald-50 border-emerald-200', rose: 'bg-rose-50 border-rose-200', purple: 'bg-purple-50 border-purple-200' };

export const StickyNotesPage: React.FC = () => {
  const [notes, setNotes] = useState<StickyNote[]>([]); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<StickyNote | null>(null); const [editorOpen, setEditorOpen] = useState(false); const [saving, setSaving] = useState(false);
  const refresh = async () => { try { setNotes(await stickyNotesService.list()); } catch { setNotes([]); } };
  useEffect(() => { void refresh(); }, []);
  const filtered = useMemo(() => notes.filter((note) => `${note.title} ${note.content}`.toLowerCase().includes(query.toLowerCase())), [notes, query]);
  const save = async (input: StickyNoteInput) => { if (!input.content.trim()) return; setSaving(true); try { const note = editing ? await stickyNotesService.update(editing.id, input) : await stickyNotesService.create(input); setNotes((prev) => editing ? prev.map((n) => n.id === note.id ? note : n) : [note, ...prev]); setEditing(null); setEditorOpen(false); } finally { setSaving(false); } };
  const remove = async (id: string) => { await stickyNotesService.remove(id); setNotes((prev) => prev.filter((note) => note.id !== id)); };
  const togglePin = async (note: StickyNote) => { const updated = await stickyNotesService.update(note.id, { title: note.title, content: note.content, colorKey: note.colorKey, isPinned: !note.isPinned }); setNotes((prev) => prev.map((n) => n.id === updated.id ? updated : n)); };
  return <div className="space-y-6 pb-12"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2"><StickyIcon className="w-6 h-6 text-indigo-600" />Sticky Notes</h1><p className="text-sm text-slate-500 mt-1">Private notes for your WidgetFlow workspace.</p></div><button type="button" onClick={() => { setEditing(null); setEditorOpen(true); }} className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-4 py-2.5 text-xs font-semibold text-white hover:bg-indigo-700"><Plus className="w-4 h-4" />New Note</button></div><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search notes…" className="w-full rounded-lg border border-slate-200 bg-white py-2 pl-9 pr-3 text-xs focus:border-indigo-500 focus:outline-none" /></div>{(['Pinned', 'All Notes'] as const).map((section) => { const sectionNotes = filtered.filter((note) => section === 'Pinned' ? note.isPinned : !note.isPinned); return <section key={section}><h2 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">{section}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sectionNotes.map((note) => <NoteCard key={note.id} note={note} onEdit={() => { setEditing(note); setEditorOpen(true); }} onDelete={() => void remove(note.id)} onPin={() => void togglePin(note)} />)}</div>{section === 'All Notes' && !filtered.length && <p className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-xs text-slate-500">No notes to show yet.</p>}</section>; })}{editorOpen && <NoteEditor note={editing} saving={saving} onCancel={() => { setEditorOpen(false); setEditing(null); }} onSave={save} />}</div>;
};

const NoteCard: React.FC<{ note: StickyNote; onEdit: () => void; onDelete: () => void; onPin: () => void }> = ({ note, onEdit, onDelete, onPin }) => <article className={`rounded-xl border p-4 shadow-xs ${colorClass[note.colorKey]}`}><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-bold text-slate-800">{note.title || 'Untitled note'}</h3><p className="mt-2 whitespace-pre-wrap text-xs text-slate-700 line-clamp-5">{note.content}</p></div><button type="button" aria-label={note.isPinned ? 'Unpin note' : 'Pin note'} onClick={onPin} className="rounded p-1 text-slate-500 hover:bg-white/70"><Pin className={`w-4 h-4 ${note.isPinned ? 'fill-current' : ''}`} /></button></div><div className="mt-4 flex items-center justify-between text-[10px] text-slate-500"><span>{new Date(note.updatedAt).toLocaleDateString()}</span><span className="flex gap-1"><button type="button" onClick={onEdit} className="rounded p-1.5 hover:bg-white/70" aria-label="Edit note"><Edit3 className="w-3.5 h-3.5" /></button><button type="button" onClick={onDelete} className="rounded p-1.5 text-rose-600 hover:bg-white/70" aria-label="Delete note"><Trash2 className="w-3.5 h-3.5" /></button></span></div></article>;

const NoteEditor: React.FC<{ note: StickyNote | null; saving: boolean; onCancel: () => void; onSave: (input: StickyNoteInput) => void }> = ({ note, saving, onCancel, onSave }) => { const [title, setTitle] = useState(note?.title ?? ''); const [content, setContent] = useState(note?.content ?? ''); const [colorKey, setColorKey] = useState<StickyNoteColor>(note?.colorKey ?? 'yellow'); const [isPinned, setIsPinned] = useState(note?.isPinned ?? false); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={(event) => { event.preventDefault(); onSave({ title, content, colorKey, isPinned }); }} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-slate-900">{note ? 'Edit Note' : 'New Note'}</h2><button type="button" onClick={onCancel} aria-label="Close"><X className="w-5 h-5 text-slate-400" /></button></div><label className="block text-xs font-semibold text-slate-700">Title<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm" /></label><label className="mt-4 block text-xs font-semibold text-slate-700">Content<textarea required value={content} onChange={(event) => setContent(event.target.value)} rows={6} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm" /></label><div className="mt-4 flex items-center gap-2">{colors.map((color) => <button type="button" key={color} aria-label={`Use ${color} color`} onClick={() => setColorKey(color)} className={`h-7 w-7 rounded-full border-2 ${colorClass[color]} ${colorKey === color ? 'ring-2 ring-indigo-500' : ''}`} />)}<button type="button" onClick={() => setIsPinned((value) => !value)} className={`ml-2 inline-flex items-center gap-1 text-xs font-semibold ${isPinned ? 'text-indigo-600' : 'text-slate-500'}`}><Pin className="w-3.5 h-3.5" />Pin</button></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-semibold">Cancel</button><button type="submit" disabled={saving || !content.trim()} className="rounded-lg bg-indigo-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save'}</button></div></form></div>; };
